# Generated by Django 4.2.1 on 2023-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to='postimages'),
        ),
    ]
