# Generated by Django 4.2.1 on 2023-06-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0002_rename_location_trip_country_trip_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='isReady',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
