# Generated by Django 4.2.1 on 2023-06-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0003_trip_isready_alter_trip_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pins',
            field=models.IntegerField(default=0),
        ),
    ]
