# Generated by Django 4.2.1 on 2023-06-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0005_alter_trip_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripID', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
