# Generated by Django 4.2.1 on 2023-05-15 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_guide_traveller_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='firstName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='lastName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guide',
            name='profilePic',
            field=models.ImageField(default='pfp.png', upload_to='profileImages'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='userID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
