# Generated by Django 4.2.1 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_guide_bio_guide_firstname_guide_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='telephone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
