# Generated by Django 4.2.1 on 2023-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_guide_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='isGuide',
            field=models.BooleanField(default=False),
        ),
    ]
