# Generated by Django 4.2.1 on 2023-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_traveller_isguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='firstName',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='guide',
            name='lastName',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='firstName',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='lastName',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
