# Generated by Django 4.2.1 on 2023-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_guide_bio_alter_guide_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='firstName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='lastName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
