# Generated by Django 4.2.1 on 2023-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_travellerpreferences_traveller_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellerpreferences',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
