# Generated by Django 4.2.1 on 2023-05-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_travellerpreferences_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='preferences',
        ),
        migrations.DeleteModel(
            name='TravellerPreferences',
        ),
    ]
