# Generated by Django 4.2.1 on 2023-05-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_traveller_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravellerPreferences',
        ),
    ]
