# Generated by Django 4.2.1 on 2023-05-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_travellerpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerPreferences',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('distance', models.CharField(blank=True, default='0', max_length=1)),
                ('interests', models.CharField(blank=True, default='0', max_length=1)),
                ('partySize', models.SmallIntegerField(blank=True, default='0')),
            ],
        ),
        migrations.AddField(
            model_name='traveller',
            name='preferences',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.travellerpreferences'),
        ),
    ]
