# Generated by Django 4.2.1 on 2023-05-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_traveller_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='preferences',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.travellerpreferences'),
        ),
    ]
