# Generated by Django 4.2.1 on 2023-05-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_traveller_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='preferences',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.travellerpreferences'),
        ),
        migrations.AlterField(
            model_name='travellerpreferences',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
