# Generated by Django 4.2.1 on 2023-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_traveller_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='firstName',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='lastName',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
