# Generated by Django 4.2.1 on 2023-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_traveller_firstname_alter_traveller_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='firstName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='lastName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
