# Generated by Django 4.2.1 on 2023-05-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_traveller_firstname_alter_traveller_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
