# Generated by Django 4.2.1 on 2023-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0005_alter_trip_description'),
        ('user', '0020_alter_traveller_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='trips',
            field=models.ManyToManyField(blank=True, default=None, to='tripsfeed.trip'),
        ),
    ]
