# Generated by Django 4.2.1 on 2023-06-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsfeed', '0005_alter_trip_description'),
        ('user', '0021_traveller_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='pinnedTrips',
            field=models.ManyToManyField(blank=True, default=None, related_name='pinnedTrips', to='tripsfeed.trip'),
        ),
    ]
