# Generated by Django 4.2.1 on 2023-06-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_traveller_pinnedtrips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='pinnedTrips',
        ),
    ]
